### ISSUE TITLE
Plans for reading .gz ?

### ISSUE THREAD

**Issue by colindaven** [OpenGene/AfterQC#6]
Hi, nice tool. 

Are there any plans for reading gzipped files in the future ? This can be quite helpful, especially when reanalyzing quality of older compressed projects.

Also, is there an internal adapter library or does AfterQC find adapters by itself in the reads ? I couldn't understand the command line help about barcodes.

Thanks.
Colin

**Comment by sfchen** [comment]
gz is already supported, if you have any problem using it to parse gz file, update here.

AfterQC currently does adapter trimming automatically if it meets:
1, it is pair-end sequencing
2, the original DNA template is shorter than sequencing cycles, so that it may sequence the adapters in the read1/read2 tail.

Note that Illumina bcl2fastq already supports some adapter trimming now, so you don't need to worry about adapter any more, except the case above.

The `barcode` in the command line help is only for `single molecule barcoding`, so just ignore that.

**Comment by colindaven** [comment]
Ok, thanks! Seems to work well.
