### ISSUE TITLE
multithreading

### ISSUE THREAD

**Issue by KField-Bucknell** [OpenGene/AfterQC#7]
Is there a way to limit the number of threads that the program uses? It looks like it is running one thread per fastq file, but I would like it to only run a limited number of threads on our HPC node. I suppose that I could run afterqc on only a limited number of fastq files at a time, but I thought that there might be a more elegant solution.
Thanks,
Ken

**Comment by sfchen** [comment]
Thanks @KField-Bucknell 
Will implement this feature.

**Comment by sfchen** [comment]
Before this thread limiting feature is implemented, you can use AfterQC for a single file/pair.

For example

``` shell
python after.py   -1 read1.fq.gz  -2 read2.fq.gz
```

Please find more details in the document

**Comment by sfchen** [comment]
I will implement this feature and make a release in this week.

**Comment by serbulent** [comment]
Hello,

I couldn't see the multihread option in any release nor in documentation after this comment. Is it implented or still in the waiting list ?

Thanks,

Serbulent

**Comment by sfchen** [comment]
@serbulent I am sorry that I haven't implemented this for AfterQC.

However, I've implemented another tool `fastp`, which provides most features of AfterQC, and is much much faster than AfterQC (10X faster), since it's developed in C++ with multithreading.

You can try `fastp` first: https://github.com/OpenGene/fastp
